### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by wallymathieu** [OnurGumus/onurgumus.github.io#1]
Hi! I noticed that there doesn't seem to be an atom or RSS feed for your site. It would be nice to be able to subscribe to your blog using standard tools.

**Comment by OnurGumus** [comment]
Hello, I didn't think there would be anyone needing it. But I will check that out:)

**Comment by OnurGumus** [comment]
Apparently, it was easy. You can use the below link

https://onurgumus.github.io/feed.xml

or an RSS link exists on the main page.
